# kubectl apply -f deployment/33-dispatch.yaml
# kubectl delete -f deployment/33-dispatch.yaml
# kubectl replace --force -f deployment/33-dispatch.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-dispatch
  namespace: falcon
  labels: {app: falcon-dispatch}
spec:
  replicas: 1
  selector: {matchLabels: {app: falcon-dispatch}}
  template:
    metadata:
      labels: {app: falcon-dispatch}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: falcon-dispatch
          image: registry.4the.company/falcon-dispatch:1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef: {name: falcon-config}
            - secretRef:    {name: falcon-secrets}
          resources:
            requests: {cpu: "100m", memory: "128Mi"}
            limits:   {cpu: "300m", memory: "256Mi"}
